### ISSUE TITLE
Increase Syringes Collected max to 500+

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#147] opened 2019-09-14 14:08 UTC

**Comment by danielljohnson** [comment] 2020-03-29 01:23
Where is this limited to 500? Far as I can tell you can keep going up.
<img width="259" alt="Screen Shot 2020-03-28 at 9 23 00 PM" src="https://user-images.githubusercontent.com/649495/77837730-5f5a0b80-713a-11ea-99f6-10bf57f72b54.png">

**Comment by danielljohnson** [comment] 2020-03-29 01:26
However, there is a bug when you go from user to user, the syringes collected field as well as others retain the value that it was set to for the last user, or at least I assume this is a bug?

**Comment by evandana** [comment] 2020-03-29 11:27
Interesting thought regarding the fields persisting values across users. 

If I was filling it out for UserA and then typed in UserB, I would expect it to either
1. Clear the form and load with UserB
2. Maintain all updated fields from UserA while merging in UserB's default fields (like gender)

While there are some nice use benefits for #2, I think #1 might be best. What do you think? I can create a new ticket.

**Comment by danielljohnson** [comment] 2020-04-09 22:31
Going to close as the bug mentioned was fixed in another ticket and I can't reproduce this specific issue. If it's important it will come back.

**Closed as completed by danielljohnson** 2020-04-09 22:31 UTC
Labels: [size1] XS, P2
