### ISSUE TITLE
Admin Handling Instructions

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#101] opened 2019-01-08 20:10 UTC
- [x] Check documentation that @ahulab wrote
- [x] Add any additional documentation (and organize this documentation)

**Comment by pandathegiant** [comment] 2019-02-03 17:13
Since this is duplicate of https://github.com/evandana/keep-ahope/issues/103, closing it, but re-opening that one for potential additional work (to be discussed)

**Closed by pandathegiant** 2019-02-03 17:13 UTC
Labels: P1, [size2] SM
