### ISSUE TITLE
Schema Initialization

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#63] opened 2018-10-11 13:15 UTC
- [ ] Create `admin` role
- [ ] Create `basic` role
- [ ] Create all classes and add ACLs (Access Control Lists)
- [ ] Ensure this would work for fresh environments

Needs a lot of updating

**Comment by pandathegiant** [comment] 2019-01-20 16:56
This issue is a duplicate of and superceded by https://github.com/evandana/keep-ahope/issues/109 and https://github.com/evandana/keep-ahope/issues/100.

**Closed by pandathegiant** 2019-01-20 16:56 UTC
Labels: P2, [size3] MED
